site_name: Trace
repo_url: https://github.com/slaclab/trace
repo_name: slaclab/trace

nav:
  - Home: index.md
  - How To:
      - Overview: how_to/overview.md
      - Traces: how_to/traces.md
      - Traces Table Menu: how_to/traces_table_menu.md
      - Axes: how_to/axes.md
      - Plot Config: how_to/plot_config.md
      - Import/Export: how_to/io.md
      - Convert Save Files: how_to/file_conversion.md
  - API Reference:
      - Trace: api_reference/trace.md
      - Traces Table: api_reference/traces_table.md
      - Axis Table: api_reference/axis_table.md
      - Plot Config: api_reference/plot_config.md

theme:
  name: material
  # custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [trace]

