name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.repository == 'slaclab/Archive-Viewer' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          channels: conda-forge
          activate-environment: archive-viewer-dev
          environment-file: environment.yml

      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/